export const JOB_HIGHLIGHT_OPTIONS = [
  {
    key: 'new_graduate_ok',
    vi: 'Ứng viên sắp tốt nghiệp OK',
    en: 'New graduates welcome',
    jp: '卒業予定者OK',
  },
  {
    key: 'no_experience_ok',
    vi: 'Chưa có kinh nghiệm OK',
    en: 'No experience required',
    jp: '未経験OK',
  },
  {
    key: 'career_break_ok',
    vi: 'Kinh nghiệm ngắt quãng OK',
    en: 'Career breaks accepted',
    jp: 'ブランクOK',
  },
  {
    key: 'interview_guaranteed',
    vi: 'Có điều kiện đảm bảo phỏng vấn',
    en: 'Interview guaranteed when basic conditions are met',
    jp: '条件を満たせば面接確約',
  },
  {
    key: 'one_round_interview',
    vi: 'Chỉ 1 vòng phỏng vấn',
    en: 'Only one interview round',
    jp: '面接1回のみ',
  },
  {
    key: 'urgent_hiring',
    vi: 'Tuyển gấp',
    en: 'Urgent hiring',
    jp: '急募',
  },
  {
    key: 'online_interview',
    vi: 'Phỏng vấn online (Web)',
    en: 'Online interview (web)',
    jp: 'オンライン面接（Web）',
  },
  {
    key: 'no_aptitude_test',
    vi: 'Không có bài test năng lực',
    en: 'No aptitude / written test',
    jp: '適性テストなし',
  },
  {
    key: 'weekend_off',
    vi: 'Nghỉ thứ 7 và Chủ nhật',
    en: 'Off on Saturdays and Sundays',
    jp: '土日休み',
  },
  {
    key: 'shift_work',
    vi: 'Làm việc theo ca',
    en: 'Shift work',
    jp: 'シフト制勤務',
  },
  {
    key: 'remote_possible',
    vi: 'Có thể làm remote',
    en: 'Remote work possible (hybrid)',
    jp: 'リモート勤務可（ハイブリッド）',
  },
  {
    key: 'full_remote',
    vi: 'Full-remote',
    en: 'Fully remote',
    jp: 'フルリモート',
  },
  {
    key: 'flex_time',
    vi: 'Giờ làm việc linh hoạt',
    en: 'Flexible working hours',
    jp: '柔軟な勤務時間／フレックスタイム制',
  },
  {
    key: 'overtime_negotiable',
    vi: 'Cho phép thương lượng làm thêm / nghỉ phép',
    en: 'Overtime / days off negotiable',
    jp: '残業・休暇の相談可',
  },
  {
    key: 'no_overtime',
    vi: 'Không làm thêm giờ',
    en: 'Little to no overtime',
    jp: '残業ほぼなし',
  },
  {
    key: 'overtime_under_10h',
    vi: 'Làm thêm không quá 10 giờ mỗi tháng',
    en: 'Overtime less than 10 hours per month',
    jp: '残業月10時間以内',
  },
  {
    key: 'overtime_under_20h',
    vi: 'Làm thêm không quá 20 giờ mỗi tháng',
    en: 'Overtime less than 20 hours per month',
    jp: '残業月20時間以内',
  },
  {
    key: 'housing_support',
    vi: 'Có nhà ở công ty / trợ cấp tiền thuê nhà',
    en: 'Company housing / housing allowance available',
    jp: '社宅・住宅手当あり',
  },
  {
    key: 'maternity_childcare_leave',
    vi: 'Có thực tế nghỉ thai sản / nghỉ chăm con',
    en: 'Maternity / childcare leave actually taken',
    jp: '産休・育休取得実績あり',
  },
  {
    key: 'foreigners_hired',
    vi: 'Có thành tích tuyển dụng người nước ngoài',
    en: 'Proven track record of hiring foreigners',
    jp: '外国人採用実績あり',
  },
  {
    key: 'use_english',
    vi: 'Có thể sử dụng tiếng Anh trong công việc',
    en: 'Able to use English at work',
    jp: '仕事で英語を活かせる',
  },
  {
    key: 'use_chinese',
    vi: 'Có thể sử dụng tiếng Trung trong công việc',
    en: 'Able to use Chinese at work',
    jp: '仕事で中国語を活かせる',
  },
  {
    key: 'use_other_language',
    vi: 'Có thể sử dụng ngoại ngữ khác trong công việc',
    en: 'Able to use other foreign languages at work',
    jp: '仕事でその他の外国語を活かせる',
  },
];

